# PHẦN 2 - DATA EXPLORATION
Mục tiêu:
- Tính tổng doanh thu, tổng lợi nhuận, tổng số lượng bán
- Tìm top 5 sản phẩm có doanh thu cao nhất
- Phân tích doanh thu theo Region và Category

## Load Cleaned Data

In [1]:
import pandas as pd

# Đọc dữ liệu đã làm sạch từ phần 1
df = pd.read_csv("orders_cleaned.csv")

# Nếu cần, chuyển lại OrderDate sang datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

df.head()

,OrderID,OrderDate,Region,Category,ProductName,Sales,Quantity,Profit,CustomerType,Month
0,1000,2023-04-13,West,Technology,Phone,199.78,8,19.84,Consumer,4
1,1001,2023-03-29,East,Office Supplies,Pen,234.00,7,-40.00,Corporate,3
2,1002,2023-05-30,East,Office Supplies,Notebook,180.18,8,27.75,Consumer,5
3,1003,2023-10-21,South,Technology,Monitor,47.08,8,10.18,Corporate,10
4,1004,2023-11-10,West,Technology,Monitor,20.37,5,2.22,Consumer,11

## Câu 1: Tổng doanh thu, lợi nhuận, số lượng

In [2]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_quantity = df["Quantity"].sum()

print("Tổng doanh thu:", total_sales)
print("Tổng lợi nhuận:", total_profit)
print("Tổng số lượng bán:", total_quantity)

Tổng doanh thu: 132649.77
Tổng lợi nhuận: 6316.74
Tổng số lượng bán: 2499

## Câu 1: Summary Table

In [3]:
summary_metrics = pd.DataFrame({
    "Metric": ["Total Sales", "Total Profit", "Total Quantity"],
    "Value": [df["Sales"].sum(), df["Profit"].sum(), df["Quantity"].sum()]
})

summary_metrics

           Metric      Value
0     Total Sales  132649.77
1    Total Profit    6316.74
2  Total Quantity    2499.00

## Câu 2: Top 5 sản phẩm doanh thu cao nhất

In [4]:
top_5_products = (
    df.groupby("ProductName", as_index=False)["Sales"]
      .sum()
      .sort_values(by="Sales", ascending=False)
      .head(5)
)

top_5_products

   ProductName     Sales
4     Notebook  12904.70
11       Table  12490.98
6          Pen  12484.61
3      Monitor  11526.33
9         Sofa  11463.13

## Câu 2: Top 5 sản phẩm kèm tỷ trọng doanh thu

In [5]:
top_5_products = top_5_products.copy()
top_5_products["Sales_Percentage"] = (
    top_5_products["Sales"] / df["Sales"].sum() * 100
).round(2)

top_5_products

   ProductName     Sales  Sales_Percentage
4     Notebook  12904.70              9.73
11       Table  12490.98              9.42
6          Pen  12484.61              9.41
3      Monitor  11526.33              8.69
9         Sofa  11463.13              8.64

## Câu 3: Doanh thu theo Region

In [6]:
sales_by_region = (
    df.groupby("Region", as_index=False)["Sales"]
      .sum()
      .sort_values(by="Sales", ascending=False)
)

sales_by_region

  Region     Sales
2  South  36324.08
0   East  34625.51
3   West  33237.22
1  North  28462.96

##  Câu 3: Doanh thu theo Category

In [7]:
sales_by_category = (
    df.groupby("Category", as_index=False)["Sales"]
      .sum()
      .sort_values(by="Sales", ascending=False)
)

sales_by_category

          Category     Sales
0        Furniture  45978.02
2       Technology  44039.21
1  Office Supplies  42632.54

## Summary

In [8]:
sales_by_category = (
    df.groupby("Category", as_index=False)["Sales"]
      .sum()
      .sort_values(by="Sales", ascending=False)
)

sales_by_category

          Category     Sales
0        Furniture  45978.02
2       Technology  44039.21
1  Office Supplies  42632.54

In [9]:
print("=== Tổng quan chỉ số ===")
print(summary_metrics)

print("\n=== Top 5 sản phẩm doanh thu cao nhất ===")
print(top_5_products)

print("\n=== Doanh thu theo Region ===")
print(sales_by_region)

print("\n=== Doanh thu theo Category ===")
print(sales_by_category)

=== Tổng quan chỉ số ===
           Metric      Value
0     Total Sales  132649.77
1    Total Profit    6316.74
2  Total Quantity    2499.00

=== Top 5 sản phẩm doanh thu cao nhất ===
   ProductName     Sales  Sales_Percentage
4     Notebook  12904.70              9.73
11       Table  12490.98              9.42
6          Pen  12484.61              9.41
3      Monitor  11526.33              8.69
9         Sofa  11463.13              8.64

=== Doanh thu theo Region ===
  Region     Sales
2  South  36324.08
0   East  34625.51
3   West  33237.22
1  North  28462.96

=== Doanh thu theo Category ===
          Category     Sales
0        Furniture  45978.02
2       Technology  44039.21
1  Office Supplies  42632.54