# PHẦN 1 - DATA CLEANING
Mục tiêu:
- Đọc dữ liệu từ file CSV
- Kiểm tra missing values
- Kiểm tra duplicate rows
- Xử lý giá trị thiếu
- Chuyển OrderDate sang datetime
- Tạo cột Month từ OrderDate

## Import Libraries

In [6]:
import pandas as pd
import numpy as np

## Read CSV File

In [7]:
# Đọc dữ liệu từ file CSV
# Đổi tên file nếu bạn lưu với tên khác
df = pd.read_csv(r"E:\AIO\Project\sales_forecasting_xai\shared\notebooks\middle_exam\sales_data5.csv")

# Xem 5 dòng đầu
df.head()

,OrderID,OrderDate,Region,Category,ProductName,Sales,Quantity,Profit,CustomerType
0,1000,2023-04-13,West,Technology,Phone,199.78,8,19.84,Consumer
1,1001,2023-03-29,East,Office Supplies,Pen,234.00,7,-40.00,Corporate
2,1002,2023-05-30,East,Office Supplies,Notebook,180.18,8,27.75,Consumer
3,1003,2023-10-21,South,Technology,Monitor,47.08,8,10.18,Corporate
4,1004,2023-11-10,West,Technology,Monitor,20.37,5,2.22,Consumer

## Overview Dataset

In [8]:
# Kiểm tra kích thước dữ liệu và kiểu dữ liệu
print("Shape:", df.shape)
df.info()

Shape: (500, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       500 non-null    int64
 1   OrderDate     500 non-null    object
 2   Region        500 non-null    object
 3   Category      500 non-null    object
 4   ProductName   500 non-null    object
 5   Sales         500 non-null    float64
 6   Quantity      500 non-null    int64
 7   Profit        500 non-null    float64
 8   CustomerType  500 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 35.3+ KB

## Check Missing Values

In [9]:
# Kiểm tra số lượng giá trị thiếu theo từng cột
missing_values = df.isnull().sum()

print("Missing values by column:")
print(missing_values)

Missing values by column:
OrderID         0
OrderDate       0
Region          0
Category        0
ProductName     0
Sales           0
Quantity        0
Profit          0
CustomerType    0
dtype: int64

## Check Duplicate Rows

In [10]:
# Kiểm tra số dòng bị trùng
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

# Hiển thị các dòng trùng nếu có
df[df.duplicated()]

Number of duplicate rows: 0

Empty DataFrame
Columns: [OrderID, OrderDate, Region, Category, ProductName, Sales, Quantity, Profit, CustomerType]
Index: []

## Handle Missing Values

In [11]:
df = df.dropna().copy()

print("Shape after handling missing values:", df.shape)
print(df.isnull().sum())

Shape after handling missing values: (500, 9)
OrderID         0
OrderDate       0
Region          0
Category        0
ProductName     0
Sales           0
Quantity        0
Profit          0
CustomerType    0
dtype: int64

## Convert OrderDate to Datetime

In [12]:
# Chuyển cột OrderDate sang datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

# Kiểm tra lại kiểu dữ liệu
print(df.dtypes)

OrderID                  int64
OrderDate       datetime64[ns]
Region                  object
Category                object
ProductName             object
Sales                  float64
Quantity                 int64
Profit                 float64
CustomerType            object
dtype: object

## Recheck Missing After Datetime Conversion

In [13]:
# Sau khi chuyển datetime, kiểm tra lại vì dữ liệu lỗi có thể thành NaT
print("Missing values after datetime conversion:")
print(df.isnull().sum())

Missing values after datetime conversion:
OrderID         0
OrderDate       0
Region          0
Category        0
ProductName     0
Sales           0
Quantity        0
Profit          0
CustomerType    0
dtype: int64

## Remove Invalid Dates If Any

In [14]:
# Xóa các dòng có OrderDate bị lỗi sau khi convert
df = df.dropna(subset=["OrderDate"]).copy()

print("Shape after removing invalid OrderDate:", df.shape)

Shape after removing invalid OrderDate: (500, 9)

## Create Month Column

In [15]:
# Tạo cột Month từ OrderDate
df["Month"] = df["OrderDate"].dt.month

df.head()

,OrderID,OrderDate,Region,Category,ProductName,Sales,Quantity,Profit,CustomerType,Month
0,1000,2023-04-13,West,Technology,Phone,199.78,8,19.84,Consumer,4
1,1001,2023-03-29,East,Office Supplies,Pen,234.00,7,-40.00,Corporate,3
2,1002,2023-05-30,East,Office Supplies,Notebook,180.18,8,27.75,Consumer,5
3,1003,2023-10-21,South,Technology,Monitor,47.08,8,10.18,Corporate,10
4,1004,2023-11-10,West,Technology,Monitor,20.37,5,2.22,Consumer,11

## Final Cleaned Data Check

In [16]:
# Kiểm tra dữ liệu sau khi làm sạch
print("Final shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

df.head()

Final shape: (500, 10)

Missing values:
OrderID         0
OrderDate       0
Region          0
Category        0
ProductName     0
Sales           0
Quantity        0
Profit          0
CustomerType    0
Month           0
dtype: int64

Duplicate rows: 0

,OrderID,OrderDate,Region,Category,ProductName,Sales,Quantity,Profit,CustomerType,Month
0,1000,2023-04-13,West,Technology,Phone,199.78,8,19.84,Consumer,4
1,1001,2023-03-29,East,Office Supplies,Pen,234.00,7,-40.00,Corporate,3
2,1002,2023-05-30,East,Office Supplies,Notebook,180.18,8,27.75,Consumer,5
3,1003,2023-10-21,South,Technology,Monitor,47.08,8,10.18,Corporate,10
4,1004,2023-11-10,West,Technology,Monitor,20.37,5,2.22,Consumer,11

## Save Cleaned Data

In [17]:
# Lưu dữ liệu đã làm sạch ra file mới
df.to_csv("orders_cleaned.csv", index=False)